//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.FAQPlusPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.FAQPlusPlus.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter de nouveaux détails sur la question.
        /// </summary>
        public static string AddQuestionSubtitle {
            get {
                return ResourceManager.GetString("AddQuestionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Réponse:**.
        /// </summary>
        public static string AnswerTitle {
            get {
                return ResourceManager.GetString("AnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandez à un expert.
        /// </summary>
        public static string AskAnExpertButtonText {
            get {
                return ResourceManager.GetString("AskAnExpertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandez à un expert.
        /// </summary>
        public static string AskAnExpertDisplayText {
            get {
                return ResourceManager.GetString("AskAnExpertDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre question détaillée et les détails à l&apos;appui ici (500 caractères maximum).
        /// </summary>
        public static string AskAnExpertPlaceholderText {
            get {
                return ResourceManager.GetString("AskAnExpertPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;expert vous répondra directement par un message de chat..
        /// </summary>
        public static string AskAnExpertSubheaderText {
            get {
                return ResourceManager.GetString("AskAnExpertSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... Si ma réponse n&apos;est pas satisfaisante ... Je vous mettrai en relation avec un expert..
        /// </summary>
        public static string AskAnExpertText2 {
            get {
                return ResourceManager.GetString("AskAnExpertText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandez à un expert.
        /// </summary>
        public static string AskAnExpertTitleText {
            get {
                return ResourceManager.GetString("AskAnExpertTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre question a été confiée à un expert. Ils vous répondront directement par un message de chat..
        /// </summary>
        public static string AssignedTicketUserNotification {
            get {
                return ResourceManager.GetString("AssignedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribué.
        /// </summary>
        public static string AssignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("AssignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribuez-moi.
        /// </summary>
        public static string AssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("AssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutonRetour.
        /// </summary>
        public static string BackButtonCommandText {
            get {
                return ResourceManager.GetString("BackButtonCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer le statut.
        /// </summary>
        public static string ChangeStatusButtonText {
            get {
                return ResourceManager.GetString("ChangeStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatter avec {0}.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proche.
        /// </summary>
        public static string CloseActionChoiceTitle {
            get {
                return ResourceManager.GetString("CloseActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermé:.
        /// </summary>
        public static string ClosedFactTitle {
            get {
                return ResourceManager.GetString("ClosedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette demande a été clôturée. Demandez à nouveau à un expert si vous avez encore besoin d&apos;aide..
        /// </summary>
        public static string ClosedTicketUserNotification {
            get {
                return ResourceManager.GetString("ClosedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermé.
        /// </summary>
        public static string ClosedUserNotificationStatus {
            get {
                return ResourceManager.GetString("ClosedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je n&apos;ai pas trouvé de réponse correspondante à cette question. Voulez-vous que je demande à un expert?.
        /// </summary>
        public static string CustomMessage {
            get {
                return ResourceManager.GetString("CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé:.
        /// </summary>
        public static string DateCreatedDisplayFactTitle {
            get {
                return ResourceManager.GetString("DateCreatedDisplayFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} à {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de bien vouloir supprimer cet élément? La question et la réponse seront supprimées..
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimé par {0}.
        /// </summary>
        public static string DeletedQnaPair {
            get {
                return ResourceManager.GetString("DeletedQnaPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description:.
        /// </summary>
        public static string DescriptionFact {
            get {
                return ResourceManager.GetString("DescriptionFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Description (Markdown pris en charge).
        /// </summary>
        public static string DescriptionLabelText {
            get {
                return ResourceManager.GetString("DescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les informations (500 caractères maximum).
        /// </summary>
        public static string DescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("DescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier les détails de la question.
        /// </summary>
        public static string EditQuestionSubtitle {
            get {
                return ResourceManager.GetString("EditQuestionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description ne peut pas être vide..
        /// </summary>
        public static string EmptyDescriptionErrorText {
            get {
                return ResourceManager.GetString("EmptyDescriptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de l&apos;image ne peut pas être vide..
        /// </summary>
        public static string EmptyImageUrlErrorText {
            get {
                return ResourceManager.GetString("EmptyImageUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le texte de la question ne peut pas être vide..
        /// </summary>
        public static string EmptyQuestionErrorText {
            get {
                return ResourceManager.GetString("EmptyQuestionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le titre ne peut pas être vide..
        /// </summary>
        public static string EmptyTitleErrorText {
            get {
                return ResourceManager.GetString("EmptyTitleErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé par.
        /// </summary>
        public static string EntryCreatedByText {
            get {
                return ResourceManager.GetString("EntryCreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelque chose a mal tourné. Veuillez réessayer plus tard..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** {0} ** a partagé les commentaires.
        /// </summary>
        public static string FeedbackAlertText {
            get {
                return ResourceManager.GetString("FeedbackAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez vos commentaires et détails de support ici (500 caractères maximum).
        /// </summary>
        public static string FeedbackDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("FeedbackDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Évaluation requise).
        /// </summary>
        public static string FeedbackRatingRequired {
            get {
                return ResourceManager.GetString("FeedbackRatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dites à mon équipe d&apos;experts comment je vais pour qu&apos;ils m&apos;aident à m&apos;améliorer..
        /// </summary>
        public static string FeedbackText1 {
            get {
                return ResourceManager.GetString("FeedbackText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poser une question.
        /// </summary>
        public static string FunctionCardText1 {
            get {
                return ResourceManager.GetString("FunctionCardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez me poser une question en la tapant dans la boîte de discussion ci-dessous, je ferai de mon mieux pour y répondre ....
        /// </summary>
        public static string FunctionCardText2 {
            get {
                return ResourceManager.GetString("FunctionCardText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aller au fil d&apos;origine.
        /// </summary>
        public static string GoToOriginalThreadButtonText {
            get {
                return ResourceManager.GetString("GoToOriginalThreadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les détails.
        /// </summary>
        public static string GoToThread {
            get {
                return ResourceManager.GetString("GoToThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utile.
        /// </summary>
        public static string HelpfulRatingText {
            get {
                return ResourceManager.GetString("HelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les balises HTML ne sont pas prises en charge..
        /// </summary>
        public static string HTMLErrorText {
            get {
                return ResourceManager.GetString("HTMLErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de l&apos;image.
        /// </summary>
        public static string ImageLabelText {
            get {
                return ResourceManager.GetString("ImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez l&apos;URL de l&apos;image (200 caractères maximum).
        /// </summary>
        public static string ImageUrlPlaceholderText {
            get {
                return ResourceManager.GetString("ImageUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de l&apos;image n&apos;est pas valide..
        /// </summary>
        public static string InvalidImageUrlErrorText {
            get {
                return ResourceManager.GetString("InvalidImageUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de redirection n&apos;est pas valide..
        /// </summary>
        public static string InvalidRedirectUrlText {
            get {
                return ResourceManager.GetString("InvalidRedirectUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification par.
        /// </summary>
        public static string LastEditedText {
            get {
                return ResourceManager.GetString("LastEditedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ de titre est obligatoire..
        /// </summary>
        public static string MandatoryTitleFieldText {
            get {
                return ResourceManager.GetString("MandatoryTitleFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question ajoutée manuellement.
        /// </summary>
        public static string ManuallyAddedQuestionMessage {
            get {
                return ResourceManager.GetString("ManuallyAddedQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A besoin d&apos;amélioration.
        /// </summary>
        public static string NeedsImprovementRatingText {
            get {
                return ResourceManager.GetString("NeedsImprovementRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;extension de messagerie ne peut être invoquée qu&apos;à partir du canal sur lequel l&apos;application est installée.
        /// </summary>
        public static string NonSMEErrorText {
            get {
                return ResourceManager.GetString("NonSMEErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inutile.
        /// </summary>
        public static string NotHelpfulRatingText {
            get {
                return ResourceManager.GetString("NotHelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&apos;ai partagé votre question avec les experts concernés. Ils vous répondront directement par un message de chat..
        /// </summary>
        public static string NotificationCardContent {
            get {
                return ResourceManager.GetString("NotificationCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir l&apos;article.
        /// </summary>
        public static string OpenArticle {
            get {
                return ResourceManager.GetString("OpenArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs facultatifs.
        /// </summary>
        public static string OptionalFieldDisplayText {
            get {
                return ResourceManager.GetString("OptionalFieldDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu.
        /// </summary>
        public static string PreviewButtonText {
            get {
                return ResourceManager.GetString("PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La question existe déjà. veuillez ajouter une question différente..
        /// </summary>
        public static string QuestionAlreadyExistsErrorText {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question posée:.
        /// </summary>
        public static string QuestionAskedFactTitle {
            get {
                return ResourceManager.GetString("QuestionAskedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** {0} ** demande une assistance..
        /// </summary>
        public static string QuestionForExpertSubHeaderText {
            get {
                return ResourceManager.GetString("QuestionForExpertSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Question.
        /// </summary>
        public static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les informations (100 caractères maximum).
        /// </summary>
        public static string QuestionPlaceholderText {
            get {
                return ResourceManager.GetString("QuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Question: ** {0}.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notation est obligatoire.
        /// </summary>
        public static string RatingMandatoryText {
            get {
                return ResourceManager.GetString("RatingMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Évaluation.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de redirection.
        /// </summary>
        public static string RedirectionLabelText {
            get {
                return ResourceManager.GetString("RedirectionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les informations (200 caractères max).
        /// </summary>
        public static string RedirectionUrlPlaceholderText {
            get {
                return ResourceManager.GetString("RedirectionUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouvrir.
        /// </summary>
        public static string ReopenActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouvrir et m&apos;attribuer.
        /// </summary>
        public static string ReopenAssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenAssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande est à nouveau ouverte. Un expert vous enverra directement un message de chat..
        /// </summary>
        public static string ReopenedTicketUserNotification {
            get {
                return ResourceManager.GetString("ReopenedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici ce que j&apos;ai trouvé:.
        /// </summary>
        public static string ResponseHeaderText {
            get {
                return ResourceManager.GetString("ResponseHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires sur les résultats.
        /// </summary>
        public static string ResultsFeedbackText {
            get {
                return ResourceManager.GetString("ResultsFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sauver.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partagez vos commentaires.
        /// </summary>
        public static string ShareFeedbackButtonText {
            get {
                return ResourceManager.GetString("ShareFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partagez vos commentaires.
        /// </summary>
        public static string ShareFeedbackDisplayText {
            get {
                return ResourceManager.GetString("ShareFeedbackDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partager les commentaires sur l&apos;application.
        /// </summary>
        public static string ShareFeedbackTitleText {
            get {
                return ResourceManager.GetString("ShareFeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le titre court ici (50 caractères maximum).
        /// </summary>
        public static string ShowCardTitleText {
            get {
                return ResourceManager.GetString("ShowCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette demande est désormais attribuée. Attribué à {0}..
        /// </summary>
        public static string SMEAssignedStatus {
            get {
                return ResourceManager.GetString("SMEAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette demande est maintenant clôturée. Fermé par {0}..
        /// </summary>
        public static string SMEClosedStatus {
            get {
                return ResourceManager.GetString("SMEClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour d&apos;information.
        /// </summary>
        public static string SMEFeedbackHeaderText {
            get {
                return ResourceManager.GetString("SMEFeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette demande n&apos;est plus affectée. Dernière mise à jour le {0}..
        /// </summary>
        public static string SMEOpenedStatus {
            get {
                return ResourceManager.GetString("SMEOpenedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribué à {0}.
        /// </summary>
        public static string SMETicketAssignedStatus {
            get {
                return ResourceManager.GetString("SMETicketAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermé.
        /// </summary>
        public static string SMETicketClosedStatus {
            get {
                return ResourceManager.GetString("SMETicketClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non attribué.
        /// </summary>
        public static string SMETicketUnassignedStatus {
            get {
                return ResourceManager.GetString("SMETicketUnassignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE: {0}.
        /// </summary>
        public static string SMEUserChatMessage {
            get {
                return ResourceManager.GetString("SMEUserChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut:.
        /// </summary>
        public static string StatusFactTitle {
            get {
                return ResourceManager.GetString("StatusFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-titre (Markdown pris en charge).
        /// </summary>
        public static string SubtitleLabelText {
            get {
                return ResourceManager.GetString("SubtitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les informations (20 caractères max).
        /// </summary>
        public static string SubtitlePlaceholderText {
            get {
                return ResourceManager.GetString("SubtitlePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les champs facultatifs ci-dessous peuvent être utilisés pour ajouter des détails supplémentaires à la réponse..
        /// </summary>
        public static string SuggestedText {
            get {
                return ResourceManager.GetString("SuggestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour d&apos;équipe.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faire un tour.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur le chat avec le bouton utilisateur pour lancer un chat direct..
        /// </summary>
        public static string TeamChatContent {
            get {
                return ResourceManager.GetString("TeamChatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initier le chat avec les utilisateurs finaux.
        /// </summary>
        public static string TeamChatHeaderText {
            get {
                return ResourceManager.GetString("TeamChatHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour, je ne supporte pas les commandes bot dans l&apos;équipe. Voici un bref aperçu de la façon dont je peux vous aider..
        /// </summary>
        public static string TeamCustomMessage {
            get {
                return ResourceManager.GetString("TeamCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez voir avec quoi les utilisateurs ont besoin d&apos;aide..
        /// </summary>
        public static string TeamNotificationContent {
            get {
                return ResourceManager.GetString("TeamNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevoir des notifications des utilisateurs finaux.
        /// </summary>
        public static string TeamNotificationHeaderText {
            get {
                return ResourceManager.GetString("TeamNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquez les demandes attribuées ou fermées pour garder une trace des requêtes..
        /// </summary>
        public static string TeamTicketSystemContent {
            get {
                return ResourceManager.GetString("TeamTicketSystemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les requêtes.
        /// </summary>
        public static string TeamTicketSystemHeaderText {
            get {
                return ResourceManager.GetString("TeamTicketSystemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci pour vos commentaires! Je l&apos;ai partagé avec les experts. Cela m&apos;aide à apprendre et à m&apos;améliorer..
        /// </summary>
        public static string ThankYouTextContent {
            get {
                return ResourceManager.GetString("ThankYouTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre:.
        /// </summary>
        public static string TitleFact {
            get {
                return ResourceManager.GetString("TitleFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre (Markdown pris en charge).
        /// </summary>
        public static string TitleLabelText {
            get {
                return ResourceManager.GetString("TitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les informations (50 caractères maximum).
        /// </summary>
        public static string TitlePlaceholderText {
            get {
                return ResourceManager.GetString("TitlePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre (obligatoire).
        /// </summary>
        public static string TitleRequiredText {
            get {
                return ResourceManager.GetString("TitleRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler l&apos;attribution.
        /// </summary>
        public static string UnassignActionChoiceTitle {
            get {
                return ResourceManager.GetString("UnassignActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non attribué.
        /// </summary>
        public static string UnassignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("UnassignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour l&apos;historique.
        /// </summary>
        public static string UpdateHistoryButtonText {
            get {
                return ResourceManager.GetString("UpdateHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string UpdateHistoryDateHeaderText {
            get {
                return ResourceManager.GetString("UpdateHistoryDateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom | Action | Date.
        /// </summary>
        public static string UpdateHistoryHeadersText {
            get {
                return ResourceManager.GetString("UpdateHistoryHeadersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir l&apos;article.
        /// </summary>
        public static string ViewArticleButtonText {
            get {
                return ResourceManager.GetString("ViewArticleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter un certain temps, les mises à jour de cette question: &quot;{0}&quot; seront disponibles sous peu..
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarque: les mises à jour sont effectuées toutes les quelques minutes.
        /// </summary>
        public static string WaitMessageAnswer {
            get {
                return ResourceManager.GetString("WaitMessageAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour équipe,
        ///
        ///Je suis votre bot Q&amp;A amical qui vous aide à fournir un soutien aux personnes qui interagissent avec moi et ont besoin de plus d&apos;assistance..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
